### ISSUE TITLE
Basic usage fails with -43

### ISSUE THREAD

**Issue by controversial** [sindresorhus/touch-bar#1]
Abbreviated console output (npm install reports no errors or warnings):
```
~/Desktop   
❯ npm i -g touch-bar
...                                                                                                                     
~/Desktop   
❯ touch-bar
Error: Command failed: open -a /Users/luke/.npm-packages/lib/node_modules/touch-bar/vendor/Touch Bar Simulator.app
FSPathMakeRef(/Users/luke/.npm-packages/lib/node_modules/touch-bar/vendor/Touch Bar Simulator.app) failed with error -43.

    at Promise.all.then.arr (/Users/luke/.npm-packages/lib/node_modules/touch-bar/node_modules/execa/index.js:208:11)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by sindresorhus** [comment]
Are you on macOS 10.12.2 or later? I forgot to mention that requirement. 

Added it now: https://github.com/sindresorhus/touch-bar/commit/e598515803959fa72fe46c9ef87634a2cbd9aeaa

**Comment by dimapaloskin** [comment]
@sindresorhus looks like "vendor" folder doesn't exist. I guess you need upgrade "files" section in the package.json file.
